version: '3.7'
services:
  zk:
    hostname: zookeeper1.dev.kafka
    container_name: ZOOKEEPER_1
    image: confluentinc/cp-zookeeper:5.5.1 
    restart: always
    labels:
      - "zookeeper.id=1"
    ports: 
      - "2181:2181"
      - "2182:2182"
      - "2888:2888"
      - "3888:3888"
    environment:
      TZ: Asia/Bangkok
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SECURE_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_DATA_DIR: /var/lib/zookeeper/data
      ZOOKEEPER_LOG_DIR: /var/lib/zookeeper/log
      ZOOKEEPER_SERVERS: zookeeper1.dev.kafka:2888:3888
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/zk_jaas.conf
             -Dzookeeper.authProvider.sasl=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
             -Dzookeeper.authProvider.x509=org.apache.zookeeper.server.auth.X509AuthenticationProvider
             -Dzookeeper.requireClientAuthScheme=sasl
             -Dzookeeper.4lw.commands.whitelist=*
             -Dzookeeper.serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory
             -Dzookeeper.ssl.keyStore.location=/etc/zookeeper/secrets/zookeeper1.keystore.jks
             -Dzookeeper.ssl.keyStore.password=changeit
             -Dzookeeper.ssl.trustStore.location=/etc/zookeeper/secrets/zookeeper1.truststore.jks
             -Dzookeeper.ssl.trustStore.password=changeit
             -Dzookeeper.ssl.client.enable=none
             -Dzookeeper.client.secure=true
             -Dzookeeper.admin.enableServer=false
    volumes:
      - D:\My_Work\Git\Kafka_SpringBoot\zk-kafka\config\zk_jaas.conf:/etc/kafka/zk_jaas.conf
      - D:\My_Work\Git\Kafka_SpringBoot\volumes\zk\data:/var/lib/zookeeper/data
      - D:\My_Work\Git\Kafka_SpringBoot\volumes\zk\log:/var/lib/zookeeper/log
      - D:\My_Work\Git\Kafka_SpringBoot\cert:/etc/zookeeper/secrets
    extra_hosts:
      - "zookeeper1.dev.kafka broker1.dev.kafka:192.168.43.145"

  broker:
    hostname: broker1.dev.kafka
    container_name: KAFKA_BROKER_1
    image: confluentinc/cp-kafka:5.5.1
    restart: always
    labels:
      - "kafka.id=1"
    ports:
      - "9092:9092"
    environment:
      TZ: Asia/Bangkok
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1.dev.kafka:2182
      KAFKA_LISTENERS: SASL_SSL://broker1.dev.kafka:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://broker1.dev.kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
      KAFKA_HEAP_OPTS: "-Xms8g -Xmx8g"
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_NUM_PARTITIONS: 8
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_METADATA_MAX_AGE_MS: 180000
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_NUM_REPLICA_FETCHERS: 2 
      ## KAFKA SSL
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker1.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: keystore_pw
      KAFKA_SSL_KEY_CREDENTIALS: sslkey_pw
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: truststore_pw
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_SSL_CLIENT_AUTH: requested
      KAFKA_SSL_ENABLED_PROTOCOLS: TLSv1.2
      ## KAFKA SASL
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      ## ---
      ## Optimize
      ## ---
      ## PRODUCER
      ## ---
      KAFKA_BATCH_SIZE: 200000
      KAFKA_LINGER_MS: 0
      KAFKA_ACKS: 1
      KAFKA_BUFFER_MEMORY: 134217728  # 128 MB
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "true"
      KAFKA_ENABLE_IDEMPOTENCE: "true"
      KAFKA_MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION: 1
      ## ---
      ## CONSUMER
      ## ---
      KAFKA_FETCH_MIN_BYTES: 1
      KAFKA_ENABLE_AUTO_COMMIT: "false"
      KAFKA_SESSION_TIMEOUT_MS: 5000

      ## --- flush if message equal to 10000000
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGE: 10000000
      ## Which one above or below
      ## --- flush if interval time equal to 60000 ms
      #KAFKA_LOG_FLUST_INTERVAL_MS: 60000
      ## ---
      KAFKA_LOG_RETENTION_HOURS: 72 # 3 days
      ## ---
      ## AUTH Basic authen
      ## ---
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/kafka_jaas.conf
              -Dzookeeper.clientCnxnSocket=org.apache.zookeeper.ClientCnxnSocketNetty
              -Dzookeeper.ssl.keyStore.location=/etc/kafka/secrets/kafkaclient.keystore.jks
              -Dzookeeper.ssl.keyStore.password=changeit
              -Dzookeeper.ssl.trustStore.location=/etc/kafka/secrets/kafkaclient.truststore.jks
              -Dzookeeper.ssl.trustStore.password=changeit
              -Dzookeeper.client.secure=true
    volumes:
      - D:\My_Work\Git\Kafka_SpringBoot\zk-kafka\config\kafka_jaas.conf:/etc/kafka/kafka_jaas.conf
      - D:\My_Work\Git\Kafka_SpringBoot\volumes\kafka:/var/lib/kafka/data
      - D:\My_Work\Git\Kafka_SpringBoot\cert:/etc/kafka/secrets
    extra_hosts:
      - "zookeeper1.dev.kafka broker1.dev.kafka:192.168.43.145"
    depends_on: 
      - zk